Fix test_install_commit_msg_hook no such file error
The test_install_commit_msg_hook will attempt to create the file
.git/hooks/commit-msg. The os.stat and os.chmod methods are not patched so fail
because the file does not exist. This change patches those two methods so the
test can pass.

======================================================================
ERROR: test_install_commit_msg_hook (gitlint.tests.test_hooks.HookTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/vagrant/.venv/local/lib/python2.7/site-packages/mock/mock.py",
    line 1305, in patched
    return func(*args, **keywargs)
  File "/vagrant/gitlint/tests/test_hooks.py", line 11, in
    test_install_commit_msg_hook
    GitHookInstaller.install_commit_msg_hook()
  File "/vagrant/gitlint/hooks.py", line 27, in install_commit_msg_hook
    st = os.stat(COMMIT_MSG_HOOK_DST_PATH)
OSError: [Errno 2] No such file or directory: '/vagrant/.git/hooks/commit-msg'