replace readfp with Python2 read_file function, to fix a test failure:
======================================================================
FAIL: test_config_file (test_cli.CLITests)
Test for --config option
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/mock.py", line 1248, in patched
    return func(*args, **keywargs)
  File "/<<PKGBUILDDIR>>/gitlint/tests/test_cli.py", line 372, in test_config_file
    self.assertEqual(result.output, "")
AssertionError: "/<<PKGBUILDDIR>>/git[197 chars]od\n" != ''
- /<<PKGBUILDDIR>>/gitlint/config.py:366: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
-   parser.readfp(config_file, filename)  # pylint: disable=deprecated-method